// states-districts.js — put this in your helpers folder
export const INDIA_STATES = [
  { id: "Andhra Pradesh", title: "Andhra Pradesh" },
  { id: "Arunachal Pradesh", title: "Arunachal Pradesh" },
  { id: "Assam", title: "Assam" },
  { id: "Bihar", title: "Bihar" },
  { id: "Chhattisgarh", title: "Chhattisgarh" },
  { id: "Goa", title: "Goa" },
  { id: "Gujarat", title: "Gujarat" },
  { id: "Haryana", title: "Haryana" },
  { id: "Himachal Pradesh", title: "Himachal Pradesh" },
  { id: "Jharkhand", title: "Jharkhand" },
  { id: "Karnataka", title: "Karnataka" },
  { id: "Kerala", title: "Kerala" },
  { id: "Madhya Pradesh", title: "Madhya Pradesh" },
  { id: "Maharashtra", title: "Maharashtra" },
  { id: "Manipur", title: "Manipur" },
  { id: "Meghalaya", title: "Meghalaya" },
  { id: "Mizoram", title: "Mizoram" },
  { id: "Nagaland", title: "Nagaland" },
  { id: "Odisha", title: "Odisha" },
  { id: "Punjab", title: "Punjab" },
  { id: "Rajasthan", title: "Rajasthan" },
  { id: "Sikkim", title: "Sikkim" },
  { id: "Tamil Nadu", title: "Tamil Nadu" },
  { id: "Telangana", title: "Telangana" },
  { id: "Tripura", title: "Tripura" },
  { id: "Uttar Pradesh", title: "Uttar Pradesh" },
  { id: "Uttarakhand", title: "Uttarakhand" },
  { id: "West Bengal", title: "West Bengal" },
  { id: "Delhi", title: "Delhi" },
  { id: "Jammu and Kashmir", title: "Jammu and Kashmir" },
  { id: "Ladakh", title: "Ladakh" },
  { id: "Puducherry", title: "Puducherry" },
  { id: "Chandigarh", title: "Chandigarh" },
  { id: "Andaman and Nicobar Islands", title: "Andaman and Nicobar Islands" },
  {
    id: "Dadra and Nagar Haveli and Daman and Diu",
    title: "Dadra and Nagar Haveli and Daman and Diu",
  },
  { id: "Lakshadweep", title: "Lakshadweep" },
];

export const DISTRICTS_BY_STATE = {
  Bihar: [
    "SARAN",
    "GAYA",
    "SAMASTIPUR",
    "BANKA",
    "ARWAL",
    "DARBHANGA",
    "GOPALGANJ",
    "PURNIA",
    "JEHANABAD",
    "ROHTAS",
    "WEST CHAMPARAN",
    "VAISHALI",
    "KISHANGANJ",
    "BHOJPUR",
    "MADHEPURA",
    "SIWAN",
    "BUXAR",
    "SAHARSA",
    "SUPAUL",
    "EAST CHAMPARAN",
    "MADHUBANI",
    "MUZAFFARPUR",
    "SITAMARHI",
    "KHAGARIA",
    "SHEOHAR",
    "NAWADA",
    "KATIHAR",
    "PATNA",
    "SHEIKHPURA",
    "AURANGABAD",
    "ARARIA",
    "BEGUSARAI",
    "BHAGALPUR",
    "MUNGER",
    "JAMUI",
    "KAIMUR BHABUA",
    "LAKHISARAI",
    "NALANDA",
  ].map((d) => ({ id: d, title: d })),

  Delhi: [
    "NORTH DELHI",
    "SOUTH WEST DELHI",
    "WEST DELHI",
    "EAST DELHI",
    "NORTH EAST DELHI",
    "SHAHDARA",
    "SOUTH DELHI",
    "NORTH WEST DELHI",
    "CENTRAL DELHI",
    "NEW DELHI",
  ].map((d) => ({ id: d, title: d })),

  Assam: [
    "KAMRUP METROPOLITAN",
    "LAKHIMPUR",
    "MARIGAON",
    "SIBSAGAR",
    "DIBRUGARH",
    "GOALPARA",
    "KARIMGANJ",
    "GOLAGHAT",
    "DIMA HASSO - NORTH CACHAR HILL",
    "DHEMAJI",
    "DARRANG",
    "NAGAON",
    "SONITPUR",
    "KAMRUP",
    "KOKRAJHAR",
    "JORHAT",
    "KARBI ANGLONG",
    "DHUBRI",
    "NALBARI",
    "BONGAIGAON",
    "TINSUKIA",
    "UDALGURI",
    "HAILAKANDI",
    "BAKSA",
    "BARPETA",
    "CACHAR",
  ].map((d) => ({ id: d, title: d })),

  Gujarat: [
    "DANGS",
    "TAPI",
    "KHEDA",
    "PANCH MAHALS",
    "JUNAGADH",
    "BANASKANTHA",
    "BHARUCH",
    "AMRELI",
    "ANAND",
    "BHAVNAGAR",
    "MORBI",
    "KACHCHH",
    "SURAT",
    "AHMEDABAD",
    "DAHOD",
    "SURENDRA NAGAR",
    "NARMADA",
    "GIR SOMNATH",
    "MAHESANA",
    "VALSAD",
    "PORBANDAR",
    "MAHISAGAR",
    "RAJKOT",
    "GANDHI NAGAR",
    "JAMNAGAR",
    "SABARKANTHA",
    "PATAN",
    "DEVBHOOMI DWERKA",
    "NAVSARI",
    "ARAVALLI",
    "VADODARA",
  ].map((d) => ({ id: d, title: d })),

  Telangana: [
    "HYDERABAD",
    "PEDDAPALLI",
    "GADWAL",
    "NALGONDA",
    "MEDAK",
    "MANCHERIAL",
    "JAGTIAL",
    "KHAMMAM",
    "SANGAREDDY",
    "NAGAR KURNOOL",
    "KAMAREDDY",
    "BHONGIR",
    "RANGAREDDY",
    "WARANGAL",
    "VIKARABAD",
    "JANGAON",
    "SURYAPET",
    "MAHABUB NAGAR",
    "NIRMAL",
    "WANAPARTHY",
    "JAYASHANKAR",
    "NIZAMABAD",
    "KARIM NAGAR",
    "ADILABAD",
    "SIDDIPET",
  ].map((d) => ({ id: d, title: d })),

  "Andhra Pradesh": [
    "BAPATLA",
    "EAST GODAVARI",
    "KURNOOL",
    "ANANTHAPUR",
    "KRISHNA",
    "KADAPA",
    "VIZIANAGARAM",
    "PRAKASAM",
    "WEST GODAVARI",
    "CHITTOOR",
    "SRIKAKULAM",
    "VISAKHAPATNAM",
    "NELLORE",
    "GUNTUR",
  ].map((d) => ({ id: d, title: d })),

  "Madhya Pradesh": [
    "GUNA",
    "SINGRAULI",
    "ANUPPUR",
    "BARWANI",
    "BETUL",
    "SEONI",
    "SHIVPURI",
    "KHANDWA",
    "DATIA",
    "ALIRAJPUR",
    "SHAJAPUR",
    "DAMOH",
    "SAGAR",
    "MANDSAUR",
    "REWA",
    "SIDHI",
    "BALAGHAT",
    "CHHINDWARA",
    "RAISEN",
    "ASHOK NAGAR",
    "MANDLA",
    "HARDA",
    "KHARGONE",
    "BHOPAL",
    "DHAR",
    "MORENA",
    "NEEMUCH",
    "HOSHANGABAD",
    "JABALPUR",
    "CHHATARPUR",
    "SHEOPUR",
    "NARSINGHPUR",
    "KATNI",
    "UMARIA",
    "SATNA",
    "BURHANPUR",
    "DINDORI",
    "SHAHDOL",
    "TIKAMGARH",
    "RAJGARH",
    "SEHORE",
    "INDORE",
    "VIDISHA",
    "JHABUA",
    "UJJAIN",
    "DEWAS",
    "GWALIOR",
    "PANNA",
    "BHIND",
    "AGAR MALWA",
    "RATLAM",
  ].map((d) => ({ id: d, title: d })),

  Karnataka: [
    "BELAGAVI",
    "CHAMARAJANAGAR",
    "HAVERI",
    "BELLARY",
    "DHARWAD",
    "KALABURAGI",
    "SHIVAMOGGA",
    "BENGALURU",
    "UTTARA KANNADA",
    "HASSAN",
    "UDUPI",
    "GADAG",
    "CHIKMAGALUR",
    "CHIKKABALLAPUR",
    "KOLAR",
    "BIDAR",
    "MANDYA",
    "BAGALKOT",
    "CHITRADURGA",
    "YADGIR",
    "DAKSHINA KANNADA",
    "RAMANAGARA",
    "BENGALURU RURAL",
    "RAICHUR",
    "TUMAKURU",
    "KOPPAL",
    "MYSURU",
    "DAVANGERE",
  ].map((d) => ({ id: d, title: d })),

  Maharashtra: [
    "RAIGARH",
    "THANE",
    "AHMED NAGAR",
    "GADCHIROLI",
    "LATUR",
    "PARBHANI",
    "GONDIA",
    "MUMBAI",
    "JALNA",
    "CHANDRAPUR",
    "NANDED",
    "WARDHA",
    "SINDHUDURG",
    "PALGHAR",
    "RATNAGIRI",
    "NANDURBAR",
    "JALGAON",
    "DHULE",
    "AKOLA",
    "HINGOLI",
    "AMRAVATI",
    "OSMANABAD",
    "KOLHAPUR",
    "WASHIM",
    "AURANGABAD",
    "NAGPUR",
    "SATARA",
    "BULDHANA",
    "PUNE",
    "BHANDARA",
    "BEED",
    "SOLAPUR",
    "NASHIK",
  ].map((d) => ({ id: d, title: d })),

  Rajasthan: [
    "JHALAWAR",
    "CHURU",
    "SRIGANGANAGAR",
    "AJMER",
    "JAIPUR",
    "ALWAR",
    "PALI",
    "BIKANER",
    "BHARATPUR",
    "SAWAI MADHOPUR",
    "BHILWARA",
    "SIKAR",
    "SIROHI",
    "DAUSA",
    "JAISALMER",
    "CHITTORGARH",
    "TONK",
    "BARAN",
    "NAGAUR",
    "HANUMANGARH",
    "UDAIPUR",
    "BUNDI",
    "JALOR",
    "BANSWARA",
    "DUNGARPUR",
    "RAJSAMAND",
    "DHOLPUR",
    "KARAULI",
    "KOTA",
    "JODHPUR",
    "BARMER",
  ].map((d) => ({ id: d, title: d })),

  "Uttar Pradesh": [
    "LUCKNOW",
    "KANPUR NAGAR",
    "AGRA",
    "VARANASI",
    "PRAYAGRAJ",
    "MEERUT",
    "GHAZIABAD",
    "GORAKHPUR",
    "ALIGARH",
    "NOIDA",
    "BAREILLY",
    "MATHURA",
    "JHANSI",
    "SITAPUR",
    "FAIZABAD",
    "AZAMGARH",
    "JAUNPUR",
    "RAEBARELI",
  ].map((d) => ({ id: d, title: d })),

  "West Bengal": [
    "NADIA",
    "SOUTH 24 PARGANAS",
    "PURULIYA",
    "NORTH 24 PARGANAS",
    "BIRBHUM",
    "DARJEELING",
    "MALDA",
    "COOCH BEHAR",
    "WEST MIDNAPORE",
    "MURSHIDABAD",
    "HOWRAH",
    "BANKURA",
    "HOOGHLY",
    "KOLKATA",
  ].map((d) => ({ id: d, title: d })),

  Kerala: [
    "ERNAKULAM",
    "KOZHIKODE",
    "PATHANAMTHITTA",
    "KANNUR",
    "KASARGOD",
    "KOLLAM",
    "MALAPPURAM",
    "WAYANAD",
    "KOTTAYAM",
    "PALAKKAD",
    "THRISSUR",
    "ALAPPUZHA",
    "THIRUVANANTHAPURAM",
    "IDUKKI",
  ].map((d) => ({ id: d, title: d })),

  "Daman and Diu": ["DAMAN", "DIU"].map((d) => ({ id: d, title: d })),

  "Jammu and Kashmir": [
    "KATHUA",
    "SHOPIAN",
    "POONCH",
    "BANDIPUR",
    "REASI",
    "SRINAGAR",
    "DODA",
    "UDHAMPUR",
    "Kargil",
    "ANANTHNAG",
    "Leh",
    "SAMBA",
    "BUDGAM",
    "JAMMU",
    "KUPWARA",
    "PULWAMA",
    "Baramulla",
    "RAMBAN",
    "GANDERBAL",
    "KULGAM",
    "RAJAURI",
  ].map((d) => ({ id: d, title: d })),

  "Tamil Nadu": [
    "DINDIGUL",
    "KARAIKAL",
    "SIVAGANGA",
    "VIRUDHUNAGAR",
    "THENI",
    "DHARMAPURI",
    "RAMANATHAPURAM",
    "TIRUNELVELI",
    "CUDDALORE",
    "THANJAVUR",
    "NAGAPATTINAM",
    "PONDICHERRY",
    "Chennai",
    "SALEM",
    "COIMBATORE",
    "VELLORE",
    "KANCHIPURAM",
    "TIRUPPUR",
    "PERAMBALUR",
    "TIRUVARUR",
    "MADURAI",
    "KARUR",
    "TIRUVALLUR",
    "VILLUPURAM",
    "ARIYALUR",
    "TIRUVANNAMALAI",
    "ERODE",
    "NILGIRIS",
    "TIRUCHIRAPPALLI",
    "KRISHNAGIRI",
    "PUDUKKOTTAI",
    "KANYAKUMARI",
    "NAMAKKAL",
    "TUTICORIN",
  ].map((d) => ({ id: d, title: d })),

  "Andaman and Nico.In.": [
    "North And Middle Andaman",
    "Nicobar",
    "South Andaman",
  ].map((d) => ({ id: d, title: d })),

  Megalaya: [
    "NA",
    "West Garo Hills",
    "Ri Bhoi",
    "Tura",
    "South Garo Hills",
    "Jaintia Hills",
    "East Garo Hills",
    "West Khasi Hills",
    "East Khasi Hills",
    "Shillong",
  ].map((d) => ({ id: d, title: d })),

  Mizoram: [
    "Champhai",
    "Mammit",
    "Lunglei",
    "NA",
    "Lawngtlai",
    "Aizawal",
    "Serchhip",
    "Saiha",
    "Kolasib",
    "Aizawl",
  ].map((d) => ({ id: d, title: d })),

  Goa: ["NORTH GOA", "SOUTH GOA"].map((d) => ({ id: d, title: d })),
  Odisha: [
    "MALKANGIRI",
    "KENDUJHAR",
    "NABARANGAPUR",
    "JAJAPUR",
    "KORAPUT",
    "PURI",
    "KALAHANDI",
    "BHADRAK",
    "GAJAPATI",
    "DEBAGARH",
    "GANJAM",
    "CUTTACK",
    "NUAPADA",
    "SONAPUR",
    "RAYAGADA",
    "BARGARH",
    "ANGUL",
    "JHARSUGUDA",
    "KHORDA",
    "BALESWAR",
    "BOUDH",
    "SAMBALPUR",
    "KANDHAMAL",
    "NAYAGARH",
    "MAYURBHANJ",
    "SUNDERGARH",
    "JAGATSINGHAPUR",
    "BALANGIR",
    "DHENKANAL",
    "KENDRAPARA",
  ].map((d) => ({ id: d, title: d })),

  Chattisgarh: [
    "BALOD",
    "Bilaspur",
    "BEMETARA",
    "SURGUJA",
    "RAIGARH",
    "DHAMTARI",
    "BALRAMPUR",
    "Dantewada",
    "BILASPURCGH",
    "RAIPUR",
    "KAWARDHA",
    "Bijapur(CGH)",
    "KORIYA",
    "Bastar",
    "JANJGIRCHAMPA",
    "MAHASAMUND",
    "SURAJPUR",
    "Jagdalpur",
    "RAJNANDGAON",
    "Kanker",
    "DURG",
    "BALOD BAZER",
    "KORBA",
    "GARIABAND",
    "JASPUR",
    "Janjgir-Champa",
    "MUNGELI",
    "Narayanpur",
  ].map((d) => ({ id: d, title: d })),
  "Dadra and Nagar Hav.": ["DADRA  NAGAR HAVELI"].map((d) => ({
    id: d,
    title: d,
  })),
  Lakshadweep: ["Kochi", "Lakshadweep"].map((d) => ({
    id: d,
    title: d,
  })),
  Sikkim: ["NORTH SIKKIM", "EAST SIKKIM", "WEST SIKKIM", "SOUTH SIKKIM"].map(
    (d) => ({
      id: d,
      title: d,
    }),
  ),
  Punjab: [
    "TARN TARAN",
    "BATHINDA",
    "FARIDKOT",
    "MUKTSAR",
    "RUPNAGAR",
    "KAPURTHALA",
    "NAWANSHAHR",
    "ROPAR",
    "FAZILKA",
    "PATHANKOT",
    "PATIALA",
    "CHANDIGHAR",
    "FATEHGARH SAHIB",
    "JALANDHAR",
    "MANSA",
    "SANGRUR",
    "LUDHIANA",
    "AMRITSAR",
    "MOGA",
    "MOHALI",
    "GURDASPUR",
    "FIROZPUR",
    "HOSHIARPUR",
  ].map((d) => ({
    id: d,
    title: d,
  })),
  Tripura: [
    "Sepahijala",
    "West Tripura",
    "Gomati",
    "Agartala ",
    "South Tripura",
    "Dharmanagar",
  ].map((d) => ({
    id: d,
    title: d,
  })),
  Jharkhand: [
    "KODERMA",
    "RANCHI",
    "GUMLA",
    "RAMGARH",
    "SIMDEGA",
    "Hazaribagh",
    "WEST SINGHBHUM",
    "GIRIDH",
    "JAMTARA",
    "PAKUR",
    "DUMKA",
    "GODDA",
    "LATEHAR",
    "SERAIKELAKHARSAWAN",
    "Lohardaga",
    "SAHIBGANJ",
    "HAZARIBAG",
    "DEOGHAR",
    "DHANBAD",
    "CHATRA",
    "PALAMAU",
    "KHUNTI",
    "EAST SINGHBHUM",
    "GARHWA",
    "BOKARO",
  ].map((d) => ({
    id: d,
    title: d,
  })),
  Haryana: [
    "FATEHABAD",
    "PANCHKULA",
    "FARIDABAD",
    "AMBALA",
    "KARNAL",
    "BHIWANI",
    "SONIPAT",
    "KURUKSHETRA",
    "MEWAT",
    "JHAJJAR",
    "GURGAON",
    "REWARI",
    "JIND",
    "KAITHAL",
    "MAHENDRAGARH",
    "YAMUNANAGAR",
    "HISAR",
    "ROHTAK",
    "PANIPAT",
    "SIRSA",
  ].map((d) => ({
    id: d,
    title: d,
  })),
  "Himachal Pradesh": [
    "BILASPUR HP",
    "KULLU",
    "SIRMAUR",
    "KINNAUR",
    "MANDI",
    "LAHUL  SPITI",
    "SHIMLA",
    "UNA",
    "CHAMBA",
    "SOLAN",
    "KANGRA",
    "HAMIRPURHP",
  ].map((d) => ({
    id: d,
    title: d,
  })),
  Uttarakhand: [
    "PITHORAGARH",
    "ALMORA",
    "UTTARKASHI",
    "BAGESHWAR",
    "TEHRI GARHWAL",
    "CHAMOLI",
    "HARIDWAR",
    "UDHAM SINGH NAGAR",
    "CHAMPAWAT",
    "DEHRADUN",
    "PAURI GARHWAL",
    "RUDRAPRAYAG",
    "NAINITAL",
  ].map((d) => ({
    id: d,
    title: d,
  })),
  "Arunachal Pradesh": [
    "East Kameng",
    "Lower Subansiri",
    "Lower Dibang Valley",
    "Papum Pare",
    "Upper Subansiri",
    "East Siang",
    "Changlang",
    "Lohit",
    "Tawang",
    "Upper Siang",
    "Tirap",
    "West Kameng",
    "West Siang",
    "Dibang Valley",
    "Kurung Kumey",
  ].map((d) => ({
    id: d,
    title: d,
  })),
  Pondicherry: ["PONDICHERRY"].map((d) => ({
    id: d,
    title: d,
  })),
  Manipur: [
    "West Tripura",
    "Imphal West",
    "Bishnupur",
    "Imphal East",
    "Tamenglong",
    "Thoubal",
    "Churachandpur",
    "Ukhrul",
    "Chandel",
    "Senapati",
  ].map((d) => ({
    id: d,
    title: d,
  })),
  Nagaland: [
    "Peren",
    "Kohima",
    "Wokha",
    "NA",
    "Dimapur",
    "Zunhebotto",
    "Tuensang",
    "Mokokchung",
    "Phek",
    "Kiphire",
    "Mon",
    "Longleng",
  ].map((d) => ({
    id: d,
    title: d,
  })),
};

export const ISSUE_TYPES = [
  { id: "Z004", title: "Warranty Complaint" },
  { id: "Z013", title: "Annual Service Contract" },
  { id: "Z014", title: "Paid Service" },
  { id: "Z003", title: "Mandatory Service Information" },
  { id: "Z002", title: "Commissioning" },
  { id: "Z043", title: "Mining Warranty" },
  { id: "Z042", title: "Mining Extended Warranty" },
  { id: "Z045", title: "Mining Goodwill" },
  { id: "Z018", title: "Parts Replacement" },
  { id: "Z019", title: "General Requirement" },
  { id: "Z038", title: "Demo & Production Study" },
  { id: "Z007", title: "Field Modification" },
  { id: "Z009", title: "Spares Promotion" },
];

export const LANGUAGES = [
  { id: "English", title: "English" },
  { id: "Hindi", title: "Hindi" },
  { id: "Telugu", title: "Telugu" },
  { id: "Kannada", title: "Kannada" },
  { id: "Tamil", title: "Tamil" },
  { id: "Malayalam", title: "Malayalam" },
  { id: "Marathi", title: "Marathi" },
  { id: "Bengali", title: "Bengali" },
  { id: "Gujarati", title: "Gujarati" },
  { id: "Oriya", title: "Oriya" },
  { id: "Others", title: "Others" },
];

export const getDistrictsByState = (stateId) => {
  return DISTRICTS_BY_STATE[stateId] || [{ id: "OTHER", title: "Other" }];
};

export const TEMPLATES = {
  PO_STATUS: {
    name: "po_status_utility_template",
    flowToken: "po_status_utility_template_flow_token",
  },
  SERVICE_TICKET: {
    name: "service_ticket_utility_template",
    flowToken: "service_ticket_utility_template_flow_token",
  },
  CREATE_TICKET: {
    name: "create_service_ticket",
    flowToken: "create_service_ticket_flow_token",
  },
  REGISTER_OPERATOR: {
    name: "register_operator",
    flowToken: "register_operator_flow_token",
  },
};

export const formatDate = (iso) =>
  new Date(iso).toLocaleString("en-IN", {
    day: "2-digit",
    month: "short",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
    hour12: true,
  });

export const formatServiceMessage = (data) => {
  return `🔧 *Service Update*

*Mobility Id:* ${data.mobilityId}
*Status:* ${data.status}
*Trip Status:* ${data.tripStatus}

*Service Order ID:* ${data.mobilityId}
*Customer Call No:* ${data.customerCallNo}
*Follow-up Call No:* ${data.followupCallNo}

*Machine Details:*
• Model: ${data.machineModel}
• Serial No: ${data.machineSerialNo}

*Engineer:* ${data.serviceEngineerName}

*Timeline:*
• Assigned: ${formatDate(data.engineerAssignedDate)}
• Resolved: ${formatDate(data.resolutionDate)}

✅ Your service request has been successfully completed.`;
};
