services:
  redis:
    image: redis:latest
    command: redis-server --maxmemory 200mb --maxmemory-policy noeviction --appendonly yes
    expose:
      - "6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    mem_limit: 300m
    networks:
      - shared-net

volumes:
  redis_data:

networks:
  shared-net:
    external: true
